spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_ROOT_USERNAME:root}:${MONGO_ROOT_PASSWORD:Mongo}@localhost:${MONGO_PORT:27018}/plantas?authSource=admin

springdoc:
  swagger-ui:
    path: /docs